# LOCALE
spring:
  web:
    locale-resolver: fixed
    locale: pt_BR

  # MYSQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/msusers?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
    username: root
    password:

  # JPA
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: false
    hibernate:
      ddl-auto: update

  #RabbitMq
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

springdoc:
  swagger-ui:
    path: /msuser.html
  api-docs:
    path: /msuser
  packages-to-scan: com.compassuol.sp.challenge.msuser.web.controller


rabbitmq:
  queue:
    name: ms_notification
  exchange:
    name: ms_notification_exchange
  routing:
    key: ms_notification_routing_key
