# LOCALE
spring:
  web:
    locale-resolver: fixed
    locale: pt_BR

  # MYSQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/msusers?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
    username: root
    password:

  # JPA
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: false
    hibernate:
      ddl-auto: update
